apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: d1
   labels:
     app: nb
     owner: gouthi1	
 spec: 
   replicas: 3
   selector:
     matchLabels:
	   app: nb
   template:
     metadata:
	   labels: 
	     app: nb
     spec:
       containers:
       - image: nginx
         name: c1